version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Building...
      - grep -Fq "basic HTML5" index.html
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
